=== sudham12345/PythonAssignments/ShoppingV1/JSON_Shopping/shoppingschema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type" : "object",
    "properties": 
     {
        "CustId"      : {"type": "integer"},
        "CustName"    : {"type": "string"},
        "CustAddress" : {"type": "string"},
        "ProductsList": {"type" :"array",
            "items" : [
                {"type" : "object",
                 "properties":
                  {
                    "ProdId" : {"type": "integer"},
                    "Qty    ": {"type": "integer"},
                    "CustAct": {"type": "string"}
                    
                   },
                "required": [
                      "ProdId",
                      "Qty",
                      "CustAct"
                   ]  
                }
            ]
        }
     },

    "required": [ "CustId" ]
}

=== sudham12345/PythonAssignments/ShoppingCart/JSON_Shopping/shoppingcart.json
{
    "CustId": 1 , 
    "CustName": "ABCD",
    "CustAddress": "NewYork",
    "ProductsList":[
        { "ProdId": 1001 , "Qty": 5 , "CustAct": "a"},
        { "ProdId": 5001 , "Qty": 3 , "CustAct": "a"},
        { "ProdId": 4001 , "Qty": 5 , "CustAct": "a"},
        { "ProdId": 1001 , "Qty": 2 , "CustAct": "r"},
        { "ProdId": 7001 , "Qty": 4 , "CustAct": "a"},
        { "ProdId": 5001 , "Qty": 5 , "CustAct": "a"},
        { "ProdId": 5001 , "Qty": 2 , "CustAct": "r"},
        { "ProdId": 7001 , "Qty": 1 , "CustAct": "r"},
        { "ProdId": 1201 , "Qty": 5 , "CustAct": "a"},
        { "ProdId": 1501 , "Qty": 3 , "CustAct": "a"},
        { "ProdId": 1801 , "Qty": 8 , "CustAct": "a"},
        { "ProdId": 1301 , "Qty": 5 , "CustAct": "a"},
        { "ProdId": 1201 , "Qty": 1 , "CustAct": "r"},
        { "ProdId": 1101 , "Qty": 5 , "CustAct": "a"},
        { "ProdId": 2001 , "Qty": 10, "CustAct": "a"},
        { "ProdId": 3001 , "Qty": 10, "CustAct": "a"},
        { "ProdId": 7001 , "Qty": 5 , "CustAct": "a"},
        { "ProdId": 2001 , "Qty": 5 , "CustAct": "r"},
        { "ProdId": 9001 , "Qty": 5 , "CustAct": "a"},
        { "ProdId": 1801 , "Qty": 10, "CustAct": "a"},
        { "ProdId": 1201 , "Qty": 3 , "CustAct": "a"},
        { "ProdId": 1601 , "Qty": 4 , "CustAct": "a"},
        { "ProdId": 5001 , "Qty": 7 , "CustAct": "a"},
        { "ProdId": 1401 , "Qty": 3 , "CustAct": "a"},
        { "ProdId": 1601 , "Qty": 1 , "CustAct": "r"},
        { "ProdId": 2001 , "Qty": 5 , "CustAct": "a"},
        { "ProdId": 2101 , "Qty": 5 , "CustAct": "a"},
        { "ProdId": 1601 , "Qty": 5 , "CustAct": "a"},
        { "ProdId": 1801 , "Qty": 3 , "CustAct": "r"},
        { "ProdId": 1101 , "Qty": 1 , "CustAct": "r"}
        ]
}
